
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/MinGW12/winlibs-x86_64-mcf-seh-gcc-13.2.0-llvm-16.0.6-mingw-w64ucrt-11.0.1-r2/mingw64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 6.2.9200 - AMD64
...
